baseURL = "https://blog.vugonz.xyz"
languageCode = "en-us"
title = "vugonz"
theme="archie"
copyright = "© vugonz"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="dark"
	# useCDN=false
	subtitle = "Welcome to my blog, hope you enjoy my funky writing abilities."

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/vugonz"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:goncalo.r.azevedo@tecnico.ulisboa.pt"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
